added option to add to DB
Liamslost/CollectionsApp pull request #3
Opened 2024-09-26 15:04 UTC by Liamslost

2024-09-26 15:09 UTC, jordanmilesbrewer commented
Peer reviewed, looks good to me

2024-09-27 08:49 UTC, mallowmew requested changes
You added a function you can unit test!!

2024-09-27 08:49 UTC, mallowmew commented on index.php
> +$All_statesData = DBgetAllDataAll_States($db);
It is conventional for variables to start with lowercase after the `$` - these variables are showing up as constants in the github php syntax highlighting. Not a functional problem, just stylistic.

2024-09-27 08:49 UTC, mallowmew commented on index.php
> +$All_statesData = DBgetAllDataAll_States($db);
I like that you get all the data at the top of the PHP file and then just call to functions ti display it in the HTML body, very organised & easy to follow.

2024-09-27 08:49 UTC, mallowmew commented on src/DBgetAllData.php
> +function DBgetAllDataUSA ($db)
It is convention for functions to start with lowercase too - `class`es in Object Oriented programming start with capital letters so the different casing is useful to disambiguate these things & will become important when we start using Object-Oriented PHP later in the course.

`DB` in function names inconsistent with your add function, which also uses the DB. I would say having `DB` in the function names is redundant - kind of obvious these thing suse the DB, but also that's an implementation detail - it's named *how* the function works, when good function names are named for *what the function does*

I also don't like the extra spaces between your function names and the opening parenthesis of the parameters - the parentheses touching the name of the function is also a way to better sight-read the code - if it has a touching paren then "you can just see" that it's a function. 

```suggestion
function dbGetAllDataUSA($db)
```

2024-09-27 08:49 UTC, mallowmew commented on src/DBgetAllData.php
> +function DBgetAllDataAll_States ($db)
Mix of camelCase and snake_case...

why not `getStates` or `getUSStates`?

2024-09-27 08:49 UTC, mallowmew commented on src/addToTable.php
> +function addToTable ($db, $data)
```suggestion
function addToTable($db, $data)
```

2024-09-27 08:49 UTC, mallowmew commented on src/populateStateDropdown.php
> +    return $options;
You can totally unit test this function, but you haven't added any yet.

2024-09-27 09:14 UTC, Liamslost commented on index.php
> +$All_statesData = DBgetAllDataAll_States($db);
done

2024-09-27 09:15 UTC, Liamslost commented on src/DBgetAllData.php
> +function DBgetAllDataUSA ($db)
that makes sense, thanks!

2024-09-27 09:15 UTC, Liamslost commented on src/DBgetAllData.php
> +function DBgetAllDataAll_States ($db)
done

2024-09-27 09:15 UTC, Liamslost commented on src/addToTable.php
> +function addToTable ($db, $data)
done

2024-09-27 10:09 UTC, Liamslost commented on src/populateStateDropdown.php
> +    return $options;
created success and malformed

2024-09-27 10:23 UTC, mallowmew requested changes
Good progress,s ome formatting issues still

2024-09-27 10:23 UTC, mallowmew commented on Tests/displayLocationsTest.php
> +class displayLocationsTest extends TestCase{
classes DO start with capital letters!

So do the files they live in.

2024-09-27 10:23 UTC, mallowmew commented on Tests/populateStateDropdownTest.php
> +            ]];
```suggestion
            ]
        ];
```

2024-09-27 10:23 UTC, mallowmew commented on index.php
> +<title>Collections App</title>
`<title>` tag goes inside the `<head>`

2024-09-27 10:23 UTC, mallowmew commented on index.php
>  <nav></nav>
`<nav>` Must go inside the body.

2024-09-27 10:33 UTC, merged